---
- hosts: localhost
  name: Create IP Pools
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: Create Edge Cluster - 01
      vmware.ansible_for_nsxt.nsxt_edge_clusters:
        hostname: "{{ nsxt_hostname }}.{{ domain }}"
        username: "{{ nsxt_admin_user }}"
        password: "{{ nsxt_password }}"
        validate_certs: "{{ nsxt_validate_certs }}"
        description: "Ansible provisionned - Edge Cluster"
        display_name: "{{ nsxt_edge_cluster_01 }}"
        #cluster_profile_bindings:
        #  - profile_name: "nsx-edge-profile"
        #    resource_type: EdgeHighAvailabilityProfile
        members:
          - transport_node_name: "{{ nsxt_edge_01_name }}"
          #- transport_node_name: "{{ nsxt_edge_02_name }}"          
        state: present
